###############################################################################
# docker.yml – AI Codegen stack
# Redis (broker), backend base image, FastAPI API, Celery worker, Dev Container
###############################################################################

services:
  # ───────────────────────────── Redis ────────────────────────────────────── #
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"

  # ─────────────── Bas-bild (Python + deps) byggs en gång ─────────────────── #
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: ai-backend:latest
    command: sleep infinity
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app/backend
    restart: unless-stopped
    depends_on:
      - redis

  # ────────────────────────── FastAPI gateway ─────────────────────────────── #
  api:
    image: ai-backend:latest
    command: >
      uvicorn backend.app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app/backend
    restart: unless-stopped
    depends_on:
      - redis
      - backend

  # ───────────────────────── Celery-worker ────────────────────────────────── #
  worker:
    image: ai-backend:latest
    command: >
      python -m celery -A backend.tasks.codegen:celery_app worker -l info -I backend.tasks.analyze
    env_file:
      - ./backend/.env
    environment:
      # Viktigt: håll dessa relativa till repo-roten i mål-repot
      TARGET_COMPONENT_DIR: frontendplay/src/components/ai
      ALLOW_PATCH: frontendplay/src/main.tsx

      # Append-läge så vi lägger till nya tiles
      AI_MOUNT_MODE: "append"

      # Stabil arbetsbranch + auto-push. PR skapas manuellt tills vidare.
      AI_WORK_BRANCH: ai/figma-work
      AUTO_PUSH: "1"
      AUTO_PR: "0"

      TZ: Europe/Stockholm
    volumes:
      - ./backend:/app/backend              # Python-koden
      - ./:/workspace                       # Valfritt: lokal workspace om du behöver den
    restart: unless-stopped
    depends_on:
      - redis
      - backend

  # ───────────── VS Code Dev Container (Node + TS + PNPM/NPM) ─────────────── #
  devcontainer:
    image: mcr.microsoft.com/devcontainers/typescript-node:20
    command: sleep infinity
    volumes:
      - ./:/workspaces/ai-codegen-extension:cached
      - node_modules:/workspaces/ai-codegen-extension/node_modules
    working_dir: /workspaces/ai-codegen-extension
    ports:
      - "3000:3000"
    environment:
      - TZ=Europe/Stockholm
    depends_on:
      - api

# ───────────────────────────── Volymer ───────────────────────────────────── #
volumes:
  node_modules: {}
